### ISSUE TITLE
Correction TP - Solution 4

### ISSUE THREAD

**Issue by khaixmania** [blegat/LSINC1113#3]
![IMG_1772](https://github.com/user-attachments/assets/587c2574-c772-4f72-9328-65bcc7182ad6)
![IMG_1773](https://github.com/user-attachments/assets/cdf9a420-77a8-44a3-8238-af08f8f7cbea)

J'ai remarqué une faute de frappe au point a) de la solution 4: **(7 + 3i) / 2** au lieu de **(3 + 7i) / 2**

**Comment by mdausort** [comment]
L'erreur a été corrigée ! Mercii
