### ISSUE TITLE
Correction TP - Solution 7 (Ex. supplémentaire)

### ISSUE THREAD

**Issue by khaixmania** [blegat/LSINC1113#4]
<img width="840" alt="Screenshot 2024-12-01 at 22 53 23" src="https://github.com/user-attachments/assets/aa6cd1cd-5320-4ad3-8d01-455ed27d8d07">
<img width="458" alt="Screenshot 2024-12-01 at 23 05 42" src="https://github.com/user-attachments/assets/30466cd8-02c0-44c2-ad0a-f25e9a4caf9a">

Les points a, b, c, d, f semblent avoir la mauvaise valeur de r après avoir retravaillé dessus.

**Comment by mdausort** [comment]
Les erreurs ont été corrigées.
